### ISSUE TITLE
xray instructions for fargate missing

### ISSUE THREAD

**Issue by murali12180** [aws-samples/aws-xray-fargate#3]
Hi, 

I don't see the instructions for the xray fargate. So far so good except I'm getting this message from service-a log:

2019-06-23 06:22:32 at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)
at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)
2019-06-23 06:22:32 at Layer.handle_error (/usr/src/app/node_modules/express/lib/router/layer.js:67:12)
at Layer.handle_error (/usr/src/app/node_modules/express/lib/router/layer.js:67:12)
2019-06-23 06:22:32Error: Failed to get the current sub/segment from the context.
Error: Failed to get the current sub/segment from the context.
2019-06-23 06:22:32 at Object.contextMissingRuntimeError [as contextMissing] (/usr/src/app/node_modules/aws-xray-sdk-core/lib/context_utils.js:21:15)
at Object.contextMissingRuntimeError [as contextMissing] (/usr/src/app/node_modules/aws-xray-sdk-core/lib/context_utils.js:21:15)
2019-06-23 06:22:32 at Object.getSegment (/usr/src/app/node_modules/aws-xray-sdk-core/lib/context_utils.js:92:45)
at Object.getSegment (/usr/src/app/node_modules/aws-xray-sdk-core/lib/context_utils.js:92:45)
2019-06-23 06:22:32 at Object.resolveSegment (/usr/src/app/node_modules/aws-xray-sdk-core/lib/context_utils.js:73:19)
at Object.resolveSegment (/usr/src/app/node_modules/aws-xray-sdk-core/lib/context_utils.js:73:19)
2019-06-23 06:22:32 at close (/usr/src/app/node_modules/aws-xray-sdk-express/lib/express_mw.js:95:29)
at close (/usr/src/app/node_modules/aws-xray-sdk-express/lib/express_mw.js:95:29)
2019-06-23 00:05:21Running on http://0.0.0.0:8080

**Comment by ss2305** [comment]
Are you running this locally ?
If so have you tried setting  ENV var on your local machine: AWS_XRAY_CONTEXT_MISSING=LOG_ERROR  ?
